// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025. 03. 03. 16:26:01
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg4 from "./../../woonuxt_base/tailwind.config.ts";
const config = [
{"content":{"files":["/Applications/XAMPP/xamppfiles/htdocs/BakonyButorKaposWoo/components/**/*.{vue,js,jsx,mjs,ts,tsx}","./components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/BakonyButorKaposWoo/woonuxt_base/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/BakonyButorKaposWoo/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/BakonyButorKaposWoo/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/BakonyButorKaposWoo/plugins/**/*.{js,ts,mjs}","/Applications/XAMPP/xamppfiles/htdocs/BakonyButorKaposWoo/composables/**/*.{js,ts,mjs}","/Applications/XAMPP/xamppfiles/htdocs/BakonyButorKaposWoo/utils/**/*.{js,ts,mjs}","/Applications/XAMPP/xamppfiles/htdocs/BakonyButorKaposWoo/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/BakonyButorKaposWoo/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/BakonyButorKaposWoo/app.config.{js,ts,mjs}"]}},
{},
{"content":{"files":["/Applications/XAMPP/xamppfiles/htdocs/BakonyButorKaposWoo/woonuxt_base/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/BakonyButorKaposWoo/woonuxt_base/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/BakonyButorKaposWoo/woonuxt_base/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/BakonyButorKaposWoo/woonuxt_base/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/BakonyButorKaposWoo/woonuxt_base/app/plugins/**/*.{js,ts,mjs}","/Applications/XAMPP/xamppfiles/htdocs/BakonyButorKaposWoo/woonuxt_base/composables/**/*.{js,ts,mjs}","/Applications/XAMPP/xamppfiles/htdocs/BakonyButorKaposWoo/woonuxt_base/utils/**/*.{js,ts,mjs}","/Applications/XAMPP/xamppfiles/htdocs/BakonyButorKaposWoo/woonuxt_base/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/BakonyButorKaposWoo/woonuxt_base/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/BakonyButorKaposWoo/woonuxt_base/app/app.config.{js,ts,mjs}","/Applications/XAMPP/xamppfiles/htdocs/BakonyButorKaposWoo/woonuxt_base/app/app/spa-loading-template.html"]}},
cfg4
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;